version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

# ----------------------------
# Executors Section
# ----------------------------
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    resource_class: medium
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    executor: android-executor

# ----------------------------
# Commands Section
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - android/change-java-version:
          java-version: 17

  setup-firebase:
    steps:
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

# ----------------------------
# Jobs Section
# ----------------------------

# Para alterar os nomes dos jobs, edite os identificadores abaixo: static-analysis-build, unit-test-and-quality-scan, deploy-to-firebase-qa

static-analysis-build:
  <<: *android_config
  steps:
    - set-android-java-version
    - checkout
    - android/restore-gradle-cache
    - run:
        name: Set Gradlew Permissions
        command: make permissions
    - run:
        name: Run Detekt
        command: make detekt
    - run:
        name: Build Staging
        command: make build-staging
    - persist_to_workspace:
        root: .
        paths:
          - build/reports/detekt
          - app/build/outputs/apk/
    - store_artifacts:
        path: build/reports/detekt
        destination: reports/detekt
    - store_artifacts:
        path: app/build/outputs/apk/
        destination: apks/
    - android/save-gradle-cache

unit-test-and-quality-scan:
  <<: *android_config
  steps:
    - set-android-java-version
    - checkout
    - attach_workspace:
        at: .
    - android/restore-gradle-cache
    - run:
        name: Clean Project
        command: make clean
    - run:
        name: Run Tests
        command: make test
    - run:
        name: Generate Coverage Reports
        command: make coverage
    - sonarcloud/scan
    - store_artifacts:
        path: build/reports/jacoco
        destination: reports/coverage
    - store_test_results:
        path: build/test-results
    - android/save-gradle-cache

deploy-to-firebase-qa:
  <<: *android_config
  steps:
    - set-android-java-version
    - checkout
    - attach_workspace:
        at: .
    - setup-firebase
    - run:
        name: Deploy to Firebase
        command: make deploy-firebase
    - store_artifacts:
        path: app/build/outputs/apk/
        destination: apks/

# ----------------------------
# Workflows Section
# ----------------------------
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Build and Analysis
      - static-analysis-build

      # Tests and Quality Gate
      - unit-test-and-quality-scan:
          requires:
            - static-analysis-build

      # Deploy to QA
      - deploy-to-firebase-qa:
          requires:
            - unit-test-and-quality-scan
          filters:
            branches:
              only: main
