version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: cimg/android:2024.01

# ----------------------------
# Commands
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - run:
          name: Set Java Version
          command: |
            java -version
            echo "JAVA_HOME=$JAVA_HOME"

# ----------------------------
# Jobs Section
# ----------------------------
jobs:
  detekt:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - set-android-java-version
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - store_artifacts:
          path: build/reports/detekt
          destination: reports/detekt
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  unit-tests-with-coverage:
    <<: *android_config
    steps:
      - checkout
      - set-android-java-version
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Unit Tests with Coverage
          command: ./gradlew test jacocoTestReport
      - store_artifacts:
          path: build/reports/jacoco
          destination: reports/coverage
      - store_test_results:
          path: build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

# ----------------------------
# Workflow Section
# ----------------------------
workflows:
  version: 2
  build-test:
    jobs:
      - detekt
      - unit-tests-with-coverage:
          requires:
            - detekt