version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

# ----------------------------
# Executors Section
# ----------------------------
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    resource_class: medium
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    executor: android-executor

# ----------------------------
# Commands Section
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - android/change-java-version:
          java-version: 17

  setup-firebase:
    steps:
      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash

  setup-keystore:
    steps:
      - run:
          name: Setup Keystore
          command: |
            # Cria o diretório se não existir
            mkdir -p "${STORE_FILE%/*}"
            # Decodifica o keystore
            echo $ENCODED_KEYSTORE | base64 -d > ${STORE_FILE}
            # Verifica se o arquivo foi criado corretamente
            if [ ! -f "${STORE_FILE}" ]; then
              echo "Keystore file does not exist"
              exit 1
            fi
            # Ajusta as permissões
            chmod 600 ${STORE_FILE}

# ----------------------------
# Jobs Section
# (Altere os nomes dos jobs abaixo se desejar: build-and-detekt, test-and-sonar, deploy-qa)
# ----------------------------
jobs:
  # Build and Static Analysis
  build-and-detekt:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - android/restore-gradle-cache
      - setup-keystore
      - run:
          name: Set Gradlew Permissions
          command: make permissions
      - run:
          name: Run Detekt
          command: make detekt
      - run:
          name: Build Staging
          command: make build-staging
      - store_artifacts:
          path: build/reports/detekt
          destination: reports/detekt
      - android/save-gradle-cache

  # Tests and Code Quality
  test-and-sonar:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - android/restore-gradle-cache
      - setup-keystore
      - run:
          name: Clean Project
          command: make clean
      - run:
          name: Run Tests
          command: make test
      - run:
          name: Generate Coverage Reports
          command: make coverage
      - sonarcloud/scan
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport-staging-unified/html
          destination: reports/coverage
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport-staging-unified/jacocoTestReport-staging-unified.xml
          destination: reports/coverage-xml
      - store_test_results:
          path: build/test-results
      - android/save-gradle-cache

  # Deployment
  deploy-qa:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - attach_workspace:
          at: .
      - setup-keystore
      - setup-firebase
      - run:
          name: Build Staging App
          command: make build-staging
      - run:
          name: Deploy to Firebase
          command: make deploy-firebase
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

# ----------------------------
# Workflows Section
# ----------------------------
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Build and Analysis
      - build-and-detekt

      # Tests and Quality Gate
      - test-and-sonar:
          requires:
            - build-and-detekt

      # Deploy to QA
      - deploy-qa:
          requires:
            - test-and-sonar
          filters:
            branches:
              only: main
