version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

# ----------------------------
# Executors Section
# ----------------------------
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    resource_class: medium
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    executor: android-executor

# ----------------------------
# Commands
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - android/change-java-version:
          java-version: 17

  setup-firebase:
    steps:
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

  decode-keystore:
    steps:
      - run:
          name: Decode Keystore
          command: |
            echo $ENCODED_KEYSTORE | base64 -d > keystore

# ----------------------------
# Jobs Section
# ----------------------------
jobs:
  detekt:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - persist_to_workspace:
          root: .
          paths:
            - build/reports/detekt
      - store_artifacts:
          path: build/reports/detekt
          destination: reports/detekt
      - android/save-gradle-cache

  test-and-sonar:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - attach_workspace:
          at: .
      - android/restore-gradle-cache
      - run:
          name: Run Tests with Coverage
          command: |
            ./gradlew test jacocoTestReportStaging
            ./gradlew collectJacocoReports
      - store_artifacts:
          path: build/reports/jacoco
          destination: reports/coverage
      - store_test_results:
          path: build/test-results
      - sonarcloud/scan
      - android/save-gradle-cache

  build-and-deploy-qa:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - setup-firebase
      - decode-keystore
      - run:
          name: Grant execute permission for gradlew
          command: chmod +x ./gradlew
      - android/restore-gradle-cache
      - run:
          name: Build QA APK
          command: ./gradlew assembleStagingRelease
      - run:
          name: Deploy to Firebase App Distribution
          command: |
            firebase appdistribution:distribute app/build/outputs/apk/staging/release/baselineProfiles/app-staging-release.apk \
              --app $FIREBASE_APP_ID \
              --groups "testers" \
              --token "$FIREBASE_TOKEN" \
              --release-notes "Build from main branch - $(git describe --tags --abbrev=0)"
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - android/save-gradle-cache

# ----------------------------
# Workflow Section
# ----------------------------
workflows:
  version: 2
  build-test-analyze:
    jobs:
      - detekt
      - test-and-sonar:
          requires:
            - detekt
      - build-and-deploy-qa:
          requires:
            - test-and-sonar
          filters:
            branches:
              only: main
