version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

# ----------------------------
# Executors Section
# ----------------------------
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    resource_class: medium
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    executor: android-executor

# ----------------------------
# Commands
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - android/change-java-version:
          java-version: 17

  setup-firebase:
    steps:
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

  decode-keystore:
    steps:
      - run:
          name: Decode Keystore
          command: |
            echo $ENCODED_KEYSTORE | base64 -d > keystore

# ----------------------------
# Jobs Section
# ----------------------------
jobs:
  analyze:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Run Code Analysis
          command: make analyze
      - store_artifacts:
          path: build/reports
      - android/save-gradle-cache

  deploy:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - setup-firebase
      - decode-keystore
      - android/restore-gradle-cache
      - run:
          name: Build and Deploy - Firebase
          command: make deploy
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - android/save-gradle-cache

# ----------------------------
# Workflow Section
# ----------------------------
workflows:
  version: 2
  build-test-analyze:
    jobs:
      - analyze
      - deploy:
          requires:
            - analyze
          filters:
            branches:
              only: main
