version: 2.1

# ----------------------------
# Orbs Section
# ----------------------------
orbs:
  android: circleci/android@2.3.0

# ----------------------------
# Executors Section
# ----------------------------
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01
    resource_class: medium
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs=-Xmx2g"

# ----------------------------
# References Section
# ----------------------------
references:
  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    executor: android-executor

# ----------------------------
# Commands Section
# ----------------------------
commands:
  set-android-java-version:
    steps:
      - android/change-java-version:
          java-version: 17

# ----------------------------
# Jobs Section
# ----------------------------
jobs:
  # Debug Environment
  debug-environment:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Debug Environment
          command: make debug-environment

  # Tests and Code Quality
  test-and-sonar:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Setup Mapbox Token
          command: make setup-mapbox
      - run:
          name: Setup Keystore
          command: make setup-keystore
      - run:
          name: Run Tests
          command: make test
      - run:
          name: Generate Coverage Reports
          command: |
            echo "Generating coverage reports..."
            make coverage

            echo "Checking generated reports..."
            find . -name "jacocoTestReport*.xml" -type f -exec echo "=== {} ===" \; -exec cat {} \;

            # Criar diretório para relatórios consolidados
            mkdir -p coverage-reports
            cp $(find . -name "jacocoTestReport*.xml") coverage-reports/ || echo "No coverage reports found"
      - run:
          name: Execute SonarQube Scanner
          command: make sonar
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport-staging-unified/html
          destination: reports/coverage
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport-staging-unified/jacocoTestReport-staging-unified.xml
          destination: reports/coverage-xml
      - store_test_results:
          path: build/test-results
      - android/save-gradle-cache

  # Deployment
  deploy-qa:
    <<: *android_config
    steps:
      - set-android-java-version
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Mapbox Token
          command: make setup-mapbox
      - run:
          name: Setup Keystore
          command: make setup-keystore
      - run:
          name: Install Firebase CLI
          command: make setup-firebase
      - run:
          name: Build Staging App
          command: make build-staging
      - run:
          name: Deploy to Firebase
          command: make deploy-firebase
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

# ----------------------------
# Workflows Section
# ----------------------------
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Debug Environment
      - debug-environment

      # Tests and Quality Gate
      - test-and-sonar:
          requires:
            - debug-environment
      - deploy-qa:
          requires:
            - test-and-sonar
          filters:
            branches:
              only: main
